### ISSUE TITLE
Test accuracy inquiry

### ISSUE THREAD

**Issue by lzyh98** [sontung/focus-tune#1]
Hello, I have read your paper and would like to use it as a baseline. I would like to ask if I used the code and methods you provided on GitHub for training and testing, but it did not meet the expected level in your paper. For example, in 7scenes_fire, the test result I obtained was 5cm/5deg: 93.3%, Median Error: 0.88deg, 2.0cm， But in your paper, the result is 5cm/5deg: 99.5%, Median Error: 0.30 / 0.77， I would like to ask you what the reason is.

**Comment by sontung** [comment]
Hi, what performance can you get with the ACE baseline?

**Comment by lzyh98** [comment]
I tested the fire scene on the ACE baseline and found that it was also slightly lower, only 5cm/5deg: 91.2%. May I ask if this is a device issue? I am using the Nvidia 4070s.

**Comment by sontung** [comment]
there might be some issues with the datasets, did you try the Cambridge dataset and see if you can get the same performance?

**Comment by lzyh98** [comment]
Thank you for your reminder. I tried the Cambridge Kings College scene. The results obtained are Median Error: 0.3deg, 18.2cm, and 5cm/5deg: 4.4%

**Comment by sontung** [comment]
That is comparable to what I obtained for the paper. I'd suggest checking the 7-scenes dataset source. Feel free to reply if you have any question.

**Comment by lzyh98** [comment]
Okay, thank you very much for your suggestion and help！
